--ここはrootでやること
----DBの作成
CREATE DATABASE its;
-- USERの作成
CREATE USER 'geocation'@'localhost' IDENTIFIED BY 'ecc';
--dbuserにCREATE権限を付与
GRANT ALL PRIVILEGES ON its.* TO 'geocation'@'localhost';
FLUSH PRIVILEGES;
-------------------------------------

--USERSテーブル
CREATE TABLE USERS (
    USER_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(254) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);
--DIARYS_POSTINGテーブル
CREATE TABLE DIARYS_POSTING (
    DIARY_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNSIGNED,
    SPOT_ID INT UNSIGNED,
    TITLE VARCHAR(64) NOT NULL,
    PHOTO VARCHAR(255),
    TEXT TEXT,
    STERGOOD DOUBLE DEFAULT 0,
    GOOD INT DEFAULT 0,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
--SPOTS_POSTINGテーブル
CREATE TABLE SPOTS_POSTING (
    SPOT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNSIGNED,
    SPOTNAME VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(161) NOT NULL,
    COST VARCHAR(10),
    REMARKS VARCHAR(255),
    PHOTO VARCHAR(255),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
-- homepageのスポットごとに表示させることに使うviewテーブル
CREATE VIEW SPOT_SAMPLE 
AS SELECT SPOT_ID, USER_ID, SPOTNAME, ADDRESS, PHOTO, COST, REMARKS, CREATED_AT
    FROM SPOTS_POSTING
    ORDER BY CREATED_AT DESC
    LIMIT 8;