--ここはrootでやること
----DBの作成
CREATE DATABASE ITS;
-- USERの作成
CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'ecc';
--dbuserにCREATE権限を付与
GRANT CREATE ON *.* TO 'dbuser'@'localhost';
--dbuserのITS領域にに全権限付与
GRANT ALL ON ITS.* TO dbuser;
--dbuserにテーブルへの参照権限を付与
GRANT SELECT ON its.DIARYS_POSTING TO 'dbuser'@'localhost';
GRANT SELECT ON its.SPOTS_POSTING TO 'dbuser'@'localhost';
GRANT SELECT ON its.USERS TO 'dbuser'@'localhost';
-------------------------------------

--USERSテーブル
CREATE TABLE USERS (
    USER_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(254) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);
--DIARYS_POSTINGテーブル
CREATE TABLE DIARYS_POSTING (
    DIARY_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNSIGNED,
    TITLE VARCHAR(64) NOT NULL,
    PHOTO VARCHAR(255),
    TEXT TEXT,
    STERGOOD DOUBLE DEFAULT 0,
    GOOD INT DEFAULT 0,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
--SPOTS_POSTINGテーブル
CREATE TABLE SPOTS_POSTING (
    SPOT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNSIGNED,
    SPOTNAME VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(161) NOT NULL,
    COST VARCHAR(10),
    REMARKS VARCHAR(255),
    PHOTO VARCHAR(255),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);